# Generated by Django 3.0.2 on 2020-02-08 21:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0005_auto_20200208_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='MapGroup',
        ),
    ]
